from __future__ import annotations

from typing import List, Optional, Protocol

from autonomy.types import DetectedObject, Goal, ObjClass


class RobotInterface(Protocol):
    """Protocol defining the contract any robot backend must satisfy."""

    held_object_id: Optional[str]

    def reset(self, seed: Optional[int] = None) -> None: ...
    def observe(self) -> List[DetectedObject]: ...
    def search(self, target_class: ObjClass) -> bool: ...
    def navigate(self, target_id: str) -> bool: ...
    def grasp(self, target_id: str) -> bool: ...
    def place_in_bin(self, target_id: str, bin_id: str) -> bool: ...
    def verify_goal(self, goal: Goal) -> bool: ...
